---
abstract: 'Find out the times at which a cron entry would run, past or future, relative to any given time'
author:
  - 'P Kent (pause@selsyn.co.uk)'
build_requires:
  DateTime: 0
  ExtUtils::MakeMaker: 0
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Schedule-Cron-Events
no_index:
  directory:
    - t
    - inc
requires:
  Set::Crontab: 0
  Time::Local: 0
version: 1.92
